# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tf_idf', [dirname(__file__)])
        except ImportError:
            import _tf_idf
            return _tf_idf
        if fp is not None:
            try:
                _mod = imp.load_module('_tf_idf', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tf_idf = swig_import_helper()
    del swig_import_helper
else:
    import _tf_idf
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tf_idf.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _tf_idf.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _tf_idf.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _tf_idf.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _tf_idf.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _tf_idf.SwigPyIterator_equal(self, x)

    def copy(self):
        return _tf_idf.SwigPyIterator_copy(self)

    def next(self):
        return _tf_idf.SwigPyIterator_next(self)

    def __next__(self):
        return _tf_idf.SwigPyIterator___next__(self)

    def previous(self):
        return _tf_idf.SwigPyIterator_previous(self)

    def advance(self, n):
        return _tf_idf.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _tf_idf.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _tf_idf.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _tf_idf.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _tf_idf.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _tf_idf.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _tf_idf.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _tf_idf.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class term_val_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, term_val_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, term_val_t, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tf_idf.term_val_t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tf_idf.term_val_t___nonzero__(self)

    def __bool__(self):
        return _tf_idf.term_val_t___bool__(self)

    def __len__(self):
        return _tf_idf.term_val_t___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _tf_idf.term_val_t___getitem__(self, key)

    def __delitem__(self, key):
        return _tf_idf.term_val_t___delitem__(self, key)

    def has_key(self, key):
        return _tf_idf.term_val_t_has_key(self, key)

    def keys(self):
        return _tf_idf.term_val_t_keys(self)

    def values(self):
        return _tf_idf.term_val_t_values(self)

    def items(self):
        return _tf_idf.term_val_t_items(self)

    def __contains__(self, key):
        return _tf_idf.term_val_t___contains__(self, key)

    def key_iterator(self):
        return _tf_idf.term_val_t_key_iterator(self)

    def value_iterator(self):
        return _tf_idf.term_val_t_value_iterator(self)

    def __setitem__(self, *args):
        return _tf_idf.term_val_t___setitem__(self, *args)

    def asdict(self):
        return _tf_idf.term_val_t_asdict(self)

    def __init__(self, *args):
        this = _tf_idf.new_term_val_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def empty(self):
        return _tf_idf.term_val_t_empty(self)

    def size(self):
        return _tf_idf.term_val_t_size(self)

    def clear(self):
        return _tf_idf.term_val_t_clear(self)

    def swap(self, v):
        return _tf_idf.term_val_t_swap(self, v)

    def get_allocator(self):
        return _tf_idf.term_val_t_get_allocator(self)

    def begin(self):
        return _tf_idf.term_val_t_begin(self)

    def end(self):
        return _tf_idf.term_val_t_end(self)

    def rbegin(self):
        return _tf_idf.term_val_t_rbegin(self)

    def rend(self):
        return _tf_idf.term_val_t_rend(self)

    def count(self, x):
        return _tf_idf.term_val_t_count(self, x)

    def erase(self, *args):
        return _tf_idf.term_val_t_erase(self, *args)

    def find(self, x):
        return _tf_idf.term_val_t_find(self, x)

    def lower_bound(self, x):
        return _tf_idf.term_val_t_lower_bound(self, x)

    def upper_bound(self, x):
        return _tf_idf.term_val_t_upper_bound(self, x)
    __swig_destroy__ = _tf_idf.delete_term_val_t
    __del__ = lambda self: None
term_val_t_swigregister = _tf_idf.term_val_t_swigregister
term_val_t_swigregister(term_val_t)

class doc_term_val_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doc_term_val_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doc_term_val_t, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tf_idf.doc_term_val_t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tf_idf.doc_term_val_t___nonzero__(self)

    def __bool__(self):
        return _tf_idf.doc_term_val_t___bool__(self)

    def __len__(self):
        return _tf_idf.doc_term_val_t___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _tf_idf.doc_term_val_t___getitem__(self, key)

    def __delitem__(self, key):
        return _tf_idf.doc_term_val_t___delitem__(self, key)

    def has_key(self, key):
        return _tf_idf.doc_term_val_t_has_key(self, key)

    def keys(self):
        return _tf_idf.doc_term_val_t_keys(self)

    def values(self):
        return _tf_idf.doc_term_val_t_values(self)

    def items(self):
        return _tf_idf.doc_term_val_t_items(self)

    def __contains__(self, key):
        return _tf_idf.doc_term_val_t___contains__(self, key)

    def key_iterator(self):
        return _tf_idf.doc_term_val_t_key_iterator(self)

    def value_iterator(self):
        return _tf_idf.doc_term_val_t_value_iterator(self)

    def __setitem__(self, *args):
        return _tf_idf.doc_term_val_t___setitem__(self, *args)

    def asdict(self):
        return _tf_idf.doc_term_val_t_asdict(self)

    def __init__(self, *args):
        this = _tf_idf.new_doc_term_val_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def empty(self):
        return _tf_idf.doc_term_val_t_empty(self)

    def size(self):
        return _tf_idf.doc_term_val_t_size(self)

    def clear(self):
        return _tf_idf.doc_term_val_t_clear(self)

    def swap(self, v):
        return _tf_idf.doc_term_val_t_swap(self, v)

    def get_allocator(self):
        return _tf_idf.doc_term_val_t_get_allocator(self)

    def begin(self):
        return _tf_idf.doc_term_val_t_begin(self)

    def end(self):
        return _tf_idf.doc_term_val_t_end(self)

    def rbegin(self):
        return _tf_idf.doc_term_val_t_rbegin(self)

    def rend(self):
        return _tf_idf.doc_term_val_t_rend(self)

    def count(self, x):
        return _tf_idf.doc_term_val_t_count(self, x)

    def erase(self, *args):
        return _tf_idf.doc_term_val_t_erase(self, *args)

    def find(self, x):
        return _tf_idf.doc_term_val_t_find(self, x)

    def lower_bound(self, x):
        return _tf_idf.doc_term_val_t_lower_bound(self, x)

    def upper_bound(self, x):
        return _tf_idf.doc_term_val_t_upper_bound(self, x)
    __swig_destroy__ = _tf_idf.delete_doc_term_val_t
    __del__ = lambda self: None
doc_term_val_t_swigregister = _tf_idf.doc_term_val_t_swigregister
doc_term_val_t_swigregister(doc_term_val_t)


def val_sum(arg1):
    return _tf_idf.val_sum(arg1)
val_sum = _tf_idf.val_sum

def term_frequency(arg1):
    return _tf_idf.term_frequency(arg1)
term_frequency = _tf_idf.term_frequency

def log_inverse_doc_frequency(arg1):
    return _tf_idf.log_inverse_doc_frequency(arg1)
log_inverse_doc_frequency = _tf_idf.log_inverse_doc_frequency

def tf_idf(arg1):
    return _tf_idf.tf_idf(arg1)
tf_idf = _tf_idf.tf_idf
# This file is compatible with both classic and new-style classes.


