# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sparse_vector', [dirname(__file__)])
        except ImportError:
            import _sparse_vector
            return _sparse_vector
        if fp is not None:
            try:
                _mod = imp.load_module('_sparse_vector', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sparse_vector = swig_import_helper()
    del swig_import_helper
else:
    import _sparse_vector
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sparse_vector.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _sparse_vector.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _sparse_vector.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _sparse_vector.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _sparse_vector.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _sparse_vector.SwigPyIterator_equal(self, x)

    def copy(self):
        return _sparse_vector.SwigPyIterator_copy(self)

    def next(self):
        return _sparse_vector.SwigPyIterator_next(self)

    def __next__(self):
        return _sparse_vector.SwigPyIterator___next__(self)

    def previous(self):
        return _sparse_vector.SwigPyIterator_previous(self)

    def advance(self, n):
        return _sparse_vector.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _sparse_vector.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _sparse_vector.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _sparse_vector.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _sparse_vector.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _sparse_vector.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _sparse_vector.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _sparse_vector.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class sparse_vector_dat_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sparse_vector_dat_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sparse_vector_dat_t, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _sparse_vector.sparse_vector_dat_t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _sparse_vector.sparse_vector_dat_t___nonzero__(self)

    def __bool__(self):
        return _sparse_vector.sparse_vector_dat_t___bool__(self)

    def __len__(self):
        return _sparse_vector.sparse_vector_dat_t___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _sparse_vector.sparse_vector_dat_t___getitem__(self, key)

    def __delitem__(self, key):
        return _sparse_vector.sparse_vector_dat_t___delitem__(self, key)

    def has_key(self, key):
        return _sparse_vector.sparse_vector_dat_t_has_key(self, key)

    def keys(self):
        return _sparse_vector.sparse_vector_dat_t_keys(self)

    def values(self):
        return _sparse_vector.sparse_vector_dat_t_values(self)

    def items(self):
        return _sparse_vector.sparse_vector_dat_t_items(self)

    def __contains__(self, key):
        return _sparse_vector.sparse_vector_dat_t___contains__(self, key)

    def key_iterator(self):
        return _sparse_vector.sparse_vector_dat_t_key_iterator(self)

    def value_iterator(self):
        return _sparse_vector.sparse_vector_dat_t_value_iterator(self)

    def __setitem__(self, *args):
        return _sparse_vector.sparse_vector_dat_t___setitem__(self, *args)

    def asdict(self):
        return _sparse_vector.sparse_vector_dat_t_asdict(self)

    def __init__(self, *args):
        this = _sparse_vector.new_sparse_vector_dat_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def empty(self):
        return _sparse_vector.sparse_vector_dat_t_empty(self)

    def size(self):
        return _sparse_vector.sparse_vector_dat_t_size(self)

    def clear(self):
        return _sparse_vector.sparse_vector_dat_t_clear(self)

    def swap(self, v):
        return _sparse_vector.sparse_vector_dat_t_swap(self, v)

    def get_allocator(self):
        return _sparse_vector.sparse_vector_dat_t_get_allocator(self)

    def begin(self):
        return _sparse_vector.sparse_vector_dat_t_begin(self)

    def end(self):
        return _sparse_vector.sparse_vector_dat_t_end(self)

    def rbegin(self):
        return _sparse_vector.sparse_vector_dat_t_rbegin(self)

    def rend(self):
        return _sparse_vector.sparse_vector_dat_t_rend(self)

    def count(self, x):
        return _sparse_vector.sparse_vector_dat_t_count(self, x)

    def erase(self, *args):
        return _sparse_vector.sparse_vector_dat_t_erase(self, *args)

    def find(self, x):
        return _sparse_vector.sparse_vector_dat_t_find(self, x)

    def lower_bound(self, x):
        return _sparse_vector.sparse_vector_dat_t_lower_bound(self, x)

    def upper_bound(self, x):
        return _sparse_vector.sparse_vector_dat_t_upper_bound(self, x)
    __swig_destroy__ = _sparse_vector.delete_sparse_vector_dat_t
    __del__ = lambda self: None
sparse_vector_dat_t_swigregister = _sparse_vector.sparse_vector_dat_t_swigregister
sparse_vector_dat_t_swigregister(sparse_vector_dat_t)

class SparseVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SparseVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SparseVector, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dat"] = _sparse_vector.SparseVector_dat_set
    __swig_getmethods__["dat"] = _sparse_vector.SparseVector_dat_get
    if _newclass:
        dat = _swig_property(_sparse_vector.SparseVector_dat_get, _sparse_vector.SparseVector_dat_set)

    def __init__(self, init_dat):
        this = _sparse_vector.new_SparseVector(init_dat)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _sparse_vector.delete_SparseVector
    __del__ = lambda self: None

    def dot_multiplication(self, *args):
        return _sparse_vector.SparseVector_dot_multiplication(self, *args)
SparseVector_swigregister = _sparse_vector.SparseVector_swigregister
SparseVector_swigregister(SparseVector)

# This file is compatible with both classic and new-style classes.


